name: voices_for_christ
description: "A mobile app for listening to messages on Voices for Christ"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #audioplayers: ^0.17.0 (not included)
  #audio_service: 0.17.0-nullsafety.0 (not included)
  audio_service: ^0.18.13
  #audio_service:
  #  git: 
  #    url: https://github.com/ryanheise/audio_service.git
  #    ref: 9c1dfc4
  audio_session: ^0.1.19
  connectivity_plus: ^1.1.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^9.1.2
  dio: ^5.4.3+1
  fluttertoast: 8.1.0
  google_fonts: ^6.2.1
  #html: ^0.14.0+4 (not included)
  http: ^1.2.1
  just_audio: ^0.9.38
  path: ^1.9.0
  path_provider: ^2.1.3
  #percent_indicator: ^2.1.9+1 (not included)
  #phone_state_i: ^0.0.3 (not included)
  scoped_model: ^2.0.0
  shared_preferences: ^2.2.3
  sliding_up_panel: ^2.0.0
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/initial_message_database.db